using System.Collections;
using UnityEngine;

public class EnemigosHandler : MonoBehaviour
{
    [SerializeField] private Transform contenedorDeEnemigos; // "Enemys"
    [SerializeField] private Canvas succesCanva;             // "End level"
    [SerializeField] private AudioClip levelPassed;
    [SerializeField] private MonoBehaviour scriptCa침on;      // Script que controla el ca침칩n

    private bool alreadyTriggered = false;
    private bool soundIsPlaying = false;

    void Start()
    {
        if (succesCanva != null)
            succesCanva.gameObject.SetActive(false);
    }

    void Update()
    {
        if (alreadyTriggered) return;

        if (TodosLosEnemigosMuertos())
        {
            alreadyTriggered = true;

            if (scriptCa침on != null)
                scriptCa침on.enabled = false; // 游댠 desactiva el ca침칩n

            succesCanva.gameObject.SetActive(true);
            Time.timeScale = 0f;

        }
    }

    private bool TodosLosEnemigosMuertos()
    {
        foreach (Transform enemigo in contenedorDeEnemigos)
        {
            if (enemigo != null && enemigo.gameObject.activeSelf)
                return false;
        }
        return true;
    }
}
